name: checks_frontend
description: "Billington â€” privacy-first receipt splitting"
publish_to: 'none'
version: 1.1.0+3

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  share_plus: ^11.0.0
  provider: ^6.1.4
  drift: ^2.15.0
  sqlite3_flutter_libs: ^0.5.20
  path_provider: ^2.1.2
  path: ^1.8.3
  url_launcher: ^6.3.1
  http: ^1.5.0
  logger: ^2.6.2
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  drift_dev: ^2.15.0
  build_runner: ^2.4.8

flutter:
  uses-material-design: true

  assets:
    - ios/Runner/Assets.xcassets/AppIcon.appiconset/breh1.png
    - assets/images/
